import type { Metadata } from "next";
import "@styles/global.scss";
import "@mantine/core/styles.css";
import { Providers } from "./_app";
import localFont from "next/font/local";
import { Header } from "@entities";

const IranYekan = localFont({
    src: [
        {
            path: "../../public/fonts/iranyekan/iranyekanwebthinfanum.woff2",
            weight: "100",
            style: "normal",
        },
        {
            path: "../../public/fonts/iranyekan/iranyekanweblightfanum.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../public/fonts/iranyekan/iranyekanwebregularfanum.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/iranyekan/iranyekanwebmediumfanum.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../../public/fonts/iranyekan/iranyekanwebboldfanum.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "../../public/fonts/iranyekan/iranyekanwebextraboldfanum.woff2",
            weight: "900",
            style: "normal",
        },
    ],
    variable: "--font-iranyekan",
});

const Gilroy = localFont({
    src: [
        {
            path: "../../public/fonts/gilroy/Gilroy-Thin.woff2",
            weight: "100",
            style: "normal",
        },
        {
            path: "../../public/fonts/gilroy/Gilroy-Light.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../public/fonts/gilroy/Gilroy-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/gilroy/Gilroy-Semibold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../../public/fonts/gilroy/Gilroy-Bold.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "../../public/fonts/gilroy/Gilroy-Extrabold.woff2",
            weight: "800",
            style: "normal",
        },
        {
            path: "../../public/fonts/gilroy/Gilroy-Black.woff2",
            weight: "900",
            style: "normal",
        },
    ],
    variable: "--font-gilroy",
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html dir="rtl" className={`${IranYekan.variable} ${Gilroy.variable}`}>
            <body>
                <Providers>
                    <Header />
                    <main>{children}</main>
                </Providers>
            </body>
        </html>
    );
}
